name: CI / Jest

on:
  pull_request:
    branches: [ main ]      # PR 要合到 main 才跑
  push:
    branches: [ main ]      # 直接推到 main（理論上被你規則擋住），保險起見也跑

permissions:
  contents: read            # 預設最小權限

concurrency:
  group: ci-${{ github.ref }}     # 同一分支/PR 的舊工作流自動取消
  cancel-in-progress: true

jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest        # 先用 GitHub runner；之後可換 self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # 若你有「必須 pin SHA」，改成對應 commit SHA

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20        # LTS
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile
      
      - name: Run tests
        run: yarn test
        env:
          CI: "true"
